export const GET_ARTICLES = "GET_ARTICLES";
export const GET_DETAIL = "GET_DETAIL";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const GET_CURRENT_ARTICLE = "GET_CURRENT_ARTICLE"; 
export const LOADING_ARTICLE = "LOADING_ARTICLE";
